workflows:
  flutter-workflow:
    name: Flutter Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      android: latest
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
      - name: Build Android App Bundle (AAB)
        script: flutter build appbundle --release
      - name: Build Web Release
        script: flutter build web --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
      - build/web
    publishing:
      email:
        recipients:
          - mohmadmossad@gmail.com

